### ISSUE TITLE
大神:请问fork这个项目后如何让开源软件模块下面显示出自己github下的项目链接

### ISSUE THREAD

**Issue by ziyekudeng** [ityouknow/ityouknow.github.io#21]
![image](https://user-images.githubusercontent.com/42562723/50628323-9ca10f00-0f72-11e9-82e5-78a307a1d241.png)
谢谢

**Comment by wyc18556** [comment]
修改_config.yml配置文件中的配置项：
```sh
repository: ${github_user_name}/${github_user_name}.github.io
github_url: https://github.com/${github_user_name}
```
其中 **${github_user_name}** 为你的github用户名，我是这样修改的，希望你的也好使--

**Comment by wyc18556** [comment]
> ![image](https://user-images.githubusercontent.com/42562723/50628323-9ca10f00-0f72-11e9-82e5-78a307a1d241.png)
> 谢谢

试试修改_config.yml配置文件中的配置项：

```shell
repository: ${github_user_name}/${github_user_name}.github.io
github_url: https://github.com/${github_user_name}
```

其中 **${github_user_name}** 为你的github用户名，我是这样修改的，希望你的也好使--
